/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RanksRouteImport } from './routes/ranks'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as KataKataIdRouteImport } from './routes/kata/$kataId'
import { Route as AdminNewRouteImport } from './routes/admin/new'
import { Route as ApiSubmissionsIndexRouteImport } from './routes/api/submissions/index'
import { Route as KataKataIdSubmissionsRouteImport } from './routes/kata/$kataId_.submissions'
import { Route as ApiAuthTestLoginRouteImport } from './routes/api/auth/test-login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminKataIdEditRouteImport } from './routes/admin/$kataId.edit'
import { Route as ApiAdminKatasIndexRouteImport } from './routes/api/admin/katas/index'
import { Route as ApiAdminKatasKataIdRouteImport } from './routes/api/admin/katas/$kataId'

const RanksRoute = RanksRouteImport.update({
  id: '/ranks',
  path: '/ranks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const KataKataIdRoute = KataKataIdRouteImport.update({
  id: '/kata/$kataId',
  path: '/kata/$kataId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/admin/new',
  path: '/admin/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmissionsIndexRoute = ApiSubmissionsIndexRouteImport.update({
  id: '/api/submissions/',
  path: '/api/submissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const KataKataIdSubmissionsRoute = KataKataIdSubmissionsRouteImport.update({
  id: '/kata/$kataId_/submissions',
  path: '/kata/$kataId/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthTestLoginRoute = ApiAuthTestLoginRouteImport.update({
  id: '/api/auth/test-login',
  path: '/api/auth/test-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKataIdEditRoute = AdminKataIdEditRouteImport.update({
  id: '/admin/$kataId/edit',
  path: '/admin/$kataId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminKatasIndexRoute = ApiAdminKatasIndexRouteImport.update({
  id: '/api/admin/katas/',
  path: '/api/admin/katas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminKatasKataIdRoute = ApiAdminKatasKataIdRouteImport.update({
  id: '/api/admin/katas/$kataId',
  path: '/api/admin/katas/$kataId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/ranks': typeof RanksRoute
  '/admin/new': typeof AdminNewRoute
  '/kata/$kataId': typeof KataKataIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/$kataId/edit': typeof AdminKataIdEditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/test-login': typeof ApiAuthTestLoginRoute
  '/kata/$kataId/submissions': typeof KataKataIdSubmissionsRoute
  '/api/submissions/': typeof ApiSubmissionsIndexRoute
  '/api/admin/katas/$kataId': typeof ApiAdminKatasKataIdRoute
  '/api/admin/katas/': typeof ApiAdminKatasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/ranks': typeof RanksRoute
  '/admin/new': typeof AdminNewRoute
  '/kata/$kataId': typeof KataKataIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/$kataId/edit': typeof AdminKataIdEditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/test-login': typeof ApiAuthTestLoginRoute
  '/kata/$kataId/submissions': typeof KataKataIdSubmissionsRoute
  '/api/submissions': typeof ApiSubmissionsIndexRoute
  '/api/admin/katas/$kataId': typeof ApiAdminKatasKataIdRoute
  '/api/admin/katas': typeof ApiAdminKatasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/ranks': typeof RanksRoute
  '/admin/new': typeof AdminNewRoute
  '/kata/$kataId': typeof KataKataIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/$kataId/edit': typeof AdminKataIdEditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/test-login': typeof ApiAuthTestLoginRoute
  '/kata/$kataId_/submissions': typeof KataKataIdSubmissionsRoute
  '/api/submissions/': typeof ApiSubmissionsIndexRoute
  '/api/admin/katas/$kataId': typeof ApiAdminKatasKataIdRoute
  '/api/admin/katas/': typeof ApiAdminKatasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/profile'
    | '/ranks'
    | '/admin/new'
    | '/kata/$kataId'
    | '/admin/'
    | '/admin/$kataId/edit'
    | '/api/auth/$'
    | '/api/auth/test-login'
    | '/kata/$kataId/submissions'
    | '/api/submissions/'
    | '/api/admin/katas/$kataId'
    | '/api/admin/katas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/profile'
    | '/ranks'
    | '/admin/new'
    | '/kata/$kataId'
    | '/admin'
    | '/admin/$kataId/edit'
    | '/api/auth/$'
    | '/api/auth/test-login'
    | '/kata/$kataId/submissions'
    | '/api/submissions'
    | '/api/admin/katas/$kataId'
    | '/api/admin/katas'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/profile'
    | '/ranks'
    | '/admin/new'
    | '/kata/$kataId'
    | '/admin/'
    | '/admin/$kataId/edit'
    | '/api/auth/$'
    | '/api/auth/test-login'
    | '/kata/$kataId_/submissions'
    | '/api/submissions/'
    | '/api/admin/katas/$kataId'
    | '/api/admin/katas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ProfileRoute: typeof ProfileRoute
  RanksRoute: typeof RanksRoute
  AdminNewRoute: typeof AdminNewRoute
  KataKataIdRoute: typeof KataKataIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminKataIdEditRoute: typeof AdminKataIdEditRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthTestLoginRoute: typeof ApiAuthTestLoginRoute
  KataKataIdSubmissionsRoute: typeof KataKataIdSubmissionsRoute
  ApiSubmissionsIndexRoute: typeof ApiSubmissionsIndexRoute
  ApiAdminKatasKataIdRoute: typeof ApiAdminKatasKataIdRoute
  ApiAdminKatasIndexRoute: typeof ApiAdminKatasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ranks': {
      id: '/ranks'
      path: '/ranks'
      fullPath: '/ranks'
      preLoaderRoute: typeof RanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kata/$kataId': {
      id: '/kata/$kataId'
      path: '/kata/$kataId'
      fullPath: '/kata/$kataId'
      preLoaderRoute: typeof KataKataIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/admin/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submissions/': {
      id: '/api/submissions/'
      path: '/api/submissions'
      fullPath: '/api/submissions/'
      preLoaderRoute: typeof ApiSubmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kata/$kataId_/submissions': {
      id: '/kata/$kataId_/submissions'
      path: '/kata/$kataId/submissions'
      fullPath: '/kata/$kataId/submissions'
      preLoaderRoute: typeof KataKataIdSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/test-login': {
      id: '/api/auth/test-login'
      path: '/api/auth/test-login'
      fullPath: '/api/auth/test-login'
      preLoaderRoute: typeof ApiAuthTestLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$kataId/edit': {
      id: '/admin/$kataId/edit'
      path: '/admin/$kataId/edit'
      fullPath: '/admin/$kataId/edit'
      preLoaderRoute: typeof AdminKataIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/katas/': {
      id: '/api/admin/katas/'
      path: '/api/admin/katas'
      fullPath: '/api/admin/katas/'
      preLoaderRoute: typeof ApiAdminKatasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/katas/$kataId': {
      id: '/api/admin/katas/$kataId'
      path: '/api/admin/katas/$kataId'
      fullPath: '/api/admin/katas/$kataId'
      preLoaderRoute: typeof ApiAdminKatasKataIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ProfileRoute: ProfileRoute,
  RanksRoute: RanksRoute,
  AdminNewRoute: AdminNewRoute,
  KataKataIdRoute: KataKataIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminKataIdEditRoute: AdminKataIdEditRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthTestLoginRoute: ApiAuthTestLoginRoute,
  KataKataIdSubmissionsRoute: KataKataIdSubmissionsRoute,
  ApiSubmissionsIndexRoute: ApiSubmissionsIndexRoute,
  ApiAdminKatasKataIdRoute: ApiAdminKatasKataIdRoute,
  ApiAdminKatasIndexRoute: ApiAdminKatasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
