/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AccountRouteImport } from './routes/account'
import { Route as KataRouteRouteImport } from './routes/kata/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as KataSlugRouteImport } from './routes/kata/$slug'
import { Route as AdminNewRouteImport } from './routes/admin/new'
import { Route as ApiSubmissionsIndexRouteImport } from './routes/api/submissions/index'
import { Route as KataSlugSubmissionsRouteImport } from './routes/kata/$slug_.submissions'
import { Route as ApiAuthTestLoginRouteImport } from './routes/api/auth/test-login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminKataIdEditRouteImport } from './routes/admin/$kataId.edit'
import { Route as ApiAdminKatasIndexRouteImport } from './routes/api/admin/katas/index'
import { Route as ApiAdminKatasKataIdRouteImport } from './routes/api/admin/katas/$kataId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const KataRouteRoute = KataRouteRouteImport.update({
  id: '/kata',
  path: '/kata',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const KataSlugRoute = KataSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KataRouteRoute,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/admin/new',
  path: '/admin/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmissionsIndexRoute = ApiSubmissionsIndexRouteImport.update({
  id: '/api/submissions/',
  path: '/api/submissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const KataSlugSubmissionsRoute = KataSlugSubmissionsRouteImport.update({
  id: '/$slug_/submissions',
  path: '/$slug/submissions',
  getParentRoute: () => KataRouteRoute,
} as any)
const ApiAuthTestLoginRoute = ApiAuthTestLoginRouteImport.update({
  id: '/api/auth/test-login',
  path: '/api/auth/test-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKataIdEditRoute = AdminKataIdEditRouteImport.update({
  id: '/admin/$kataId/edit',
  path: '/admin/$kataId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminKatasIndexRoute = ApiAdminKatasIndexRouteImport.update({
  id: '/api/admin/katas/',
  path: '/api/admin/katas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminKatasKataIdRoute = ApiAdminKatasKataIdRouteImport.update({
  id: '/api/admin/katas/$kataId',
  path: '/api/admin/katas/$kataId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kata': typeof KataRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/admin/new': typeof AdminNewRoute
  '/kata/$slug': typeof KataSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/$kataId/edit': typeof AdminKataIdEditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/test-login': typeof ApiAuthTestLoginRoute
  '/kata/$slug/submissions': typeof KataSlugSubmissionsRoute
  '/api/submissions/': typeof ApiSubmissionsIndexRoute
  '/api/admin/katas/$kataId': typeof ApiAdminKatasKataIdRoute
  '/api/admin/katas/': typeof ApiAdminKatasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kata': typeof KataRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/admin/new': typeof AdminNewRoute
  '/kata/$slug': typeof KataSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/$kataId/edit': typeof AdminKataIdEditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/test-login': typeof ApiAuthTestLoginRoute
  '/kata/$slug/submissions': typeof KataSlugSubmissionsRoute
  '/api/submissions': typeof ApiSubmissionsIndexRoute
  '/api/admin/katas/$kataId': typeof ApiAdminKatasKataIdRoute
  '/api/admin/katas': typeof ApiAdminKatasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kata': typeof KataRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/admin/new': typeof AdminNewRoute
  '/kata/$slug': typeof KataSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/$kataId/edit': typeof AdminKataIdEditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/test-login': typeof ApiAuthTestLoginRoute
  '/kata/$slug_/submissions': typeof KataSlugSubmissionsRoute
  '/api/submissions/': typeof ApiSubmissionsIndexRoute
  '/api/admin/katas/$kataId': typeof ApiAdminKatasKataIdRoute
  '/api/admin/katas/': typeof ApiAdminKatasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kata'
    | '/account'
    | '/dashboard'
    | '/admin/new'
    | '/kata/$slug'
    | '/admin/'
    | '/admin/$kataId/edit'
    | '/api/auth/$'
    | '/api/auth/test-login'
    | '/kata/$slug/submissions'
    | '/api/submissions/'
    | '/api/admin/katas/$kataId'
    | '/api/admin/katas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kata'
    | '/account'
    | '/dashboard'
    | '/admin/new'
    | '/kata/$slug'
    | '/admin'
    | '/admin/$kataId/edit'
    | '/api/auth/$'
    | '/api/auth/test-login'
    | '/kata/$slug/submissions'
    | '/api/submissions'
    | '/api/admin/katas/$kataId'
    | '/api/admin/katas'
  id:
    | '__root__'
    | '/'
    | '/kata'
    | '/account'
    | '/dashboard'
    | '/admin/new'
    | '/kata/$slug'
    | '/admin/'
    | '/admin/$kataId/edit'
    | '/api/auth/$'
    | '/api/auth/test-login'
    | '/kata/$slug_/submissions'
    | '/api/submissions/'
    | '/api/admin/katas/$kataId'
    | '/api/admin/katas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KataRouteRoute: typeof KataRouteRouteWithChildren
  AccountRoute: typeof AccountRoute
  DashboardRoute: typeof DashboardRoute
  AdminNewRoute: typeof AdminNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminKataIdEditRoute: typeof AdminKataIdEditRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthTestLoginRoute: typeof ApiAuthTestLoginRoute
  ApiSubmissionsIndexRoute: typeof ApiSubmissionsIndexRoute
  ApiAdminKatasKataIdRoute: typeof ApiAdminKatasKataIdRoute
  ApiAdminKatasIndexRoute: typeof ApiAdminKatasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kata': {
      id: '/kata'
      path: '/kata'
      fullPath: '/kata'
      preLoaderRoute: typeof KataRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kata/$slug': {
      id: '/kata/$slug'
      path: '/$slug'
      fullPath: '/kata/$slug'
      preLoaderRoute: typeof KataSlugRouteImport
      parentRoute: typeof KataRouteRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/admin/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submissions/': {
      id: '/api/submissions/'
      path: '/api/submissions'
      fullPath: '/api/submissions/'
      preLoaderRoute: typeof ApiSubmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kata/$slug_/submissions': {
      id: '/kata/$slug_/submissions'
      path: '/$slug/submissions'
      fullPath: '/kata/$slug/submissions'
      preLoaderRoute: typeof KataSlugSubmissionsRouteImport
      parentRoute: typeof KataRouteRoute
    }
    '/api/auth/test-login': {
      id: '/api/auth/test-login'
      path: '/api/auth/test-login'
      fullPath: '/api/auth/test-login'
      preLoaderRoute: typeof ApiAuthTestLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$kataId/edit': {
      id: '/admin/$kataId/edit'
      path: '/admin/$kataId/edit'
      fullPath: '/admin/$kataId/edit'
      preLoaderRoute: typeof AdminKataIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/katas/': {
      id: '/api/admin/katas/'
      path: '/api/admin/katas'
      fullPath: '/api/admin/katas/'
      preLoaderRoute: typeof ApiAdminKatasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/katas/$kataId': {
      id: '/api/admin/katas/$kataId'
      path: '/api/admin/katas/$kataId'
      fullPath: '/api/admin/katas/$kataId'
      preLoaderRoute: typeof ApiAdminKatasKataIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface KataRouteRouteChildren {
  KataSlugRoute: typeof KataSlugRoute
  KataSlugSubmissionsRoute: typeof KataSlugSubmissionsRoute
}

const KataRouteRouteChildren: KataRouteRouteChildren = {
  KataSlugRoute: KataSlugRoute,
  KataSlugSubmissionsRoute: KataSlugSubmissionsRoute,
}

const KataRouteRouteWithChildren = KataRouteRoute._addFileChildren(
  KataRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KataRouteRoute: KataRouteRouteWithChildren,
  AccountRoute: AccountRoute,
  DashboardRoute: DashboardRoute,
  AdminNewRoute: AdminNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminKataIdEditRoute: AdminKataIdEditRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthTestLoginRoute: ApiAuthTestLoginRoute,
  ApiSubmissionsIndexRoute: ApiSubmissionsIndexRoute,
  ApiAdminKatasKataIdRoute: ApiAdminKatasKataIdRoute,
  ApiAdminKatasIndexRoute: ApiAdminKatasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
